---
- name: Install and configure Docker
  hosts: bastion, web_monitoring, security_audit
  become: true

  tasks:
    - name: Refreshing the apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

#- name: Deploy Web and Monitoring Zone (server 1)

- name: Deploy Security Audit Zone (server 2)
  hosts: security_audit
  become: true

  tasks:
    - name: Create audit folder
      file:
        path: /home/ubuntu/network-audit
        state: directory
        mode: '0755'
        owner: ubuntu

    - name: Create reports folder
      file:
        path: /home/ubuntu/network-audit/reports
        state: directory
        mode: '0755'
        owner: ubuntu

    - name: Copy infra-guard
      copy:
        src: ../../python-scripts/infra-guard/
        dest: /home/ubuntu/network-audit/infra-guard

    - name: Copy config.yaml
      template:
        src: ../templates/config.yaml
        dest: /home/ubuntu/network-audit/infra-guard/config.yaml
        mode: '0644'

    - name: Build Docker Image for infra-guard
      docker_image:
        name: infra-guard-app
        build:
          path: /home/ubuntu/network-audit/infra-guard
          nocache: yes
        source: build

    - name: Run infra-guard
      docker_container:
        name: infra-guard-launch
        image: infra-guard-app
        state: present
        restart_policy: "no"
        command: "--config /app/infra-guard/config.yaml"
        network_mode: host
        volumes:
          - /home/ubuntu/network-audit/infra-guard:/app/infra-guard
        env:
          SSH_PRIVATE_KEY: "{{ lookup('file', '~/.ssh/id_ed25519') }}"