---
- name: Install and configure Docker
  hosts: web_servers
  become: true

  tasks:
    - name: Refreshing the apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

#Заготовка
#     - name: Create directory for Nginx config
#       file: 
#         path: /etc/nginx-docker
#         state: directory
#         mode: '0755'

#     - name: Copy nginx.conf to server
#       copy: 
#         src: nginx-config/nginx.conf
#         dest: /etc/nginx-docker/nginx.conf

#     - name: Run Nginx container
#       community.general.docker_container:
#         name: "nginx-proxy"
#         image: "nginx:alpine"
#         state: started
#         restart_policy: always
#         ports: [ "80:80" ]
#         volumes: [ "/etc/nginx-docker/nginx.conf:/etc/nginx/conf.d/default.conf" ] 

#     - name: Schedule Port Security Monitor via Cron
#       cron:
#         name: "run_port_security_monitor"
#         minute: "*/50"
#         job: "docker run --rm -v /var/log/microservices:/app/logs monitoring-image:latest -f /app/ports.txt --host 10.10.10.11"
          