[bastion]
bastion_host ansible_host=51.250.80.0

[web_monitoring]
web_server_1 ansible_host=10.10.10.18 ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@51.250.80.0'"

[security_audit]
web_server_2 ansible_host=10.10.10.11 ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@51.250.80.0'"
