name: Run Git Commit Audit

on:
  push:
    branches: [ "main" ]

jobs:
  run_scan:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Run Port Scanner
        working-directory: ./python-scripts/audit_tools
        run: |
          python net_audit.py

      - name: Run Git History Secrets Audit
        working-directory: ./python-scripts/audit_tools
        run: |
          python audit.py --repo ../../ --search "(key|secret|token|password)\s*=\s*['\"].+['\"]"
